//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class OrdersTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdersTb()
        {
            this.OrderProductTb = new ObservableCollection<OrderProductTb>();
        }
    
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual CustomerTb CustomerTb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<OrderProductTb> OrderProductTb { get; set; }
    }
}
