//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class OrderProductTb
    {
        public int OrderProductID { get; set; }
        public int ProductID { get; set; }
        public int OrderID { get; set; }
    
        public virtual OrdersTb OrdersTb { get; set; }
        public virtual ProductTb ProductTb { get; set; }
    }
}
